=== markdarling321/EFSC_Summer-2021_COP-4849_Web-Apps/004_Week 4  --  Project 3 - DTD & XML/Project 3/employee.dtd
<!-- DTD document for employee.xml -->

<!ELEMENT employee ( emprecord+ )>

<!ELEMENT emprecord ( empno, ename, job, mgr, hiredate, sal, comm, deptno )>

<!ELEMENT empno ( #PCDATA )>
<!ELEMENT ename ( #PCDATA )>
<!ELEMENT job ( #PCDATA )>
<!ELEMENT mgr ( #PCDATA )>
<!ELEMENT hiredate ( #PCDATA )>
<!ELEMENT sal ( #PCDATA )>
<!ELEMENT comm ( #PCDATA )>
<!ELEMENT deptno ( #PCDATA )>

=== markdarling321/EFSC_Summer-2021_COP-4849_Web-Apps/004_Week 4  --  Project 3 - DTD & XML/Project 3/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- employee.xml -->
<!-- Employee table structured with XML -->
<!DOCTYPE employee SYSTEM "employee.dtd">

<employee>
	<emprecord>
		<empno>7839</empno>
		<ename>King</ename>
		<job>President</job>
		<mgr></mgr>
		<hiredate>1981-11-17</hiredate>
		<sal>5000.00</sal>
		<comm></comm>
		<deptno>10</deptno>
	</emprecord>
	<emprecord>
		<empno>7698</empno>
		<ename>Blake</ename>
		<job>Manager</job>
		<mgr>7839</mgr>
		<hiredate>1981-05-01</hiredate>
		<sal>2850.00</sal>
		<comm></comm>
		<deptno>30</deptno>
	</emprecord>
	<emprecord>
		<empno>7782</empno>
		<ename>Clark</ename>
		<job>Manager</job>
		<mgr>7839</mgr>
		<hiredate>1981-06-09</hiredate>
		<sal>2450.00</sal>
		<comm></comm>
		<deptno>10</deptno>
	</emprecord>
	<emprecord>
		<empno>7566</empno>
		<ename>Jones</ename>
		<job>Manager</job>
		<mgr>7839</mgr>
		<hiredate>1981-04-02</hiredate>
		<sal>2975.00</sal>
		<comm></comm>
		<deptno>20</deptno>
	</emprecord>
	<emprecord>
		<empno>7654</empno>
		<ename>Martin</ename>
		<job>Salesman</job>
		<mgr>7698</mgr>
		<hiredate>1981-09-28</hiredate>
		<sal>1250.00</sal>
		<comm>1400.00</comm>
		<deptno>30</deptno>
	</emprecord>
	<emprecord>
		<empno>7499</empno>
		<ename>Allen</ename>
		<job>Salesman</job>
		<mgr>7698</mgr>
		<hiredate>1981-02-20</hiredate>
		<sal>1600.00</sal>
		<comm>300.00</comm>
		<deptno>30</deptno>
	</emprecord>
	<emprecord>
		<empno>7844</empno>
		<ename>Turner</ename>
		<job>Salesman</job>
		<mgr>7698</mgr>
		<hiredate>1981-09-08</hiredate>
		<sal>1500.00</sal>
		<comm>0.00</comm>
		<deptno>30</deptno>
	</emprecord>
	<emprecord>
		<empno>7900</empno>
		<ename>James</ename>
		<job>Clerk</job>
		<mgr>7698</mgr>
		<hiredate>1981-12-03</hiredate>
		<sal>950.00</sal>
		<comm></comm>
		<deptno>30</deptno>
	</emprecord>
	<emprecord>
		<empno>7521</empno>
		<ename>Ward</ename>
		<job>Salesman</job>
		<mgr>7698</mgr>
		<hiredate>1981-02-22</hiredate>
		<sal>1250.00</sal>
		<comm>500.00</comm>
		<deptno>30</deptno>
	</emprecord>
	<emprecord>
		<empno>7902</empno>
		<ename>Ford</ename>
		<job>Analyst</job>
		<mgr>7566</mgr>
		<hiredate>1981-12-03</hiredate>
		<sal>3000.00</sal>
		<comm></comm>
		<deptno>20</deptno>
	</emprecord>
	<emprecord>
		<empno>7369</empno>
		<ename>Smith</ename>
		<job>Clerk</job>
		<mgr>7902</mgr>
		<hiredate>1980-12-17</hiredate>
		<sal>800.00</sal>
		<comm></comm>
		<deptno>20</deptno>
	</emprecord>
	<emprecord>
		<empno>7788</empno>
		<ename>Scott</ename>
		<job>Analyst</job>
		<mgr>7566</mgr>
		<hiredate>1982-12-09</hiredate>
		<sal>3000.00</sal>
		<comm></comm>
		<deptno>20</deptno>
	</emprecord>
	<emprecord>
		<empno>7876</empno>
		<ename>Adams</ename>
		<job>Clerk</job>
		<mgr>7788</mgr>
		<hiredate>1983-01-12</hiredate>
		<sal>1100.00</sal>
		<comm></comm>
		<deptno>20</deptno>
	</emprecord>
	<emprecord>
		<empno>7934</empno>
		<ename>Miller</ename>
		<job>Clerk</job>
		<mgr>7782</mgr>
		<hiredate>1982-01-23</hiredate>
		<sal>1300.00</sal>
		<comm></comm>
		<deptno>10</deptno>
	</emprecord>
</employee>
